
###########################################################
# My Github Actions workflow. Pushes to Github Container Registry
###########################################################

name: Docker Build & Push to GHCR

on: workflow_dispatch  # Set to allow manual trigger in browser webapp

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the build on Github Actions Ubuntu worker node in cloud.
    steps:
    - uses: actions/checkout@v2  # Use existing Action to get source code.

    - name: Log in to the Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t ghcr.io/djl2/nodejs:1.0.0
    - name: docker push
      run: |
        docker push ghcr.io/djl2/nodejs:1.0.0