
###########################################################
# My Github Actions workflow. Pushes to Github Container Registry
###########################################################

name: Docker Build & Push to GHCR

on: workflow_dispatch  # Set to allow manual trigger in browser webapp

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the build on Github Actions Ubuntu worker node in cloud.
    steps:
    - uses: actions/checkout@v2  # Use existing Action to get source code.

    - name: Log in to the Github Container registry # Uses the GH Action written by the Docker team (a bit strange IMO)
      uses: docker/login-action@v2  # See https://github.com/docker/login-action
      with:
        registry: ghcr.io   # The default github Container Registry url
        username: ${{ github.actor }}  # See https://github.com/docker/login-action#github-container-registry
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t ghcr.io/djl2/nodejs
    - name: docker push
      run: |
        docker push ghcr.io/djl2/nodejs
      # To see published Docker images, go to your Github account>packages

