
###########################################################
# My custom workflow file. Based on docker._yaml example
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Use existing Action to get source code.
    - name: docker build csharp
      run: |  # Use the pipe for multiline string to run multiple builds 
        docker build ./c# -t aimvector/csharp:1.0.0
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t aimvector/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build ./python -t aimvector/python:1.0.0
#    - name: docker build golang   # Removed due to build errors.
#      run: |
#        docker build ./golang -t aimvector/golang:1.0.0
        
